### ISSUE TITLE
ToDo's from "Meeting"

### ISSUE THREAD

**Issue by GamerBene19** [mensatt/frontend-old#149]
- [x] Reverse Comment Order
- [ ] Add dropdown to specifiy sort order of comments (desc/asc by rating, ...)
- [ ] #121 
- [ ] Add possibility to rotate images prior to uploading
- [ ] Limit amount of comments show
